### ISSUE TITLE
Guideline for logger integration

### ISSUE THREAD

**Issue by xavierchow** [Wiredcraft/coding-standard-n-strategies#6]
@ChopperLee2011 Please help to wrap up some best practice and guideline for logger integration, e.g.
- which npm to use for logging
- How to integrate with loopback
- How to configure
- Where(Which case) to write the log 
...

**Comment by ChopperLee2011** [comment]
firstly, most of our backend logging strategy is ELK stack and input source is syslog, so basically what this logger integration is also a way to write information to syslog.

secondly, about these questions:
> Which npm to use for logging
https://github.com/Wiredcraft/bunyan-logger, if you feel any uncomfortable about using this lib, please create a ticket under that ticket.

> How to integrate with loopback
1. init logger when booting
2. create a middleware which invokes before restful api is handling. [a demo link](https://github.com/starbucks-china/ams-public/blob/master/server/middleware/logger/index.js)
3. other inline logging or debug logging, you can still use bunyan-logger.

>How to configure
here is part of bunyan-logger [README](https://github.com/Wiredcraft/bunyan-logger#predefined-streams)

>Where(Which case) to write the log
for a restful api, you need to write basic request info and response info to log, don't forget a transaction id field which we can trace logs between serval components. And if a function which is calling inside a request, you should log some step information, also don't forget a transaction id. What's more, `ERRORS`,  better have a http status code and error code to identify each cases.
here is a struct example for logging request and response:
```
request {
      type: 'HTTP',
      direction: 'IN',
      actionType: 'REQ',
      target,
      targetModule,
      transactionId,
      appId,
      statusCode
}

response {
          type: 'HTTP',
          direction: 'OUT',
          actionType: 'RESP',
          target,
          targetModule,
          transactionId,
          appId,
          statusCode
}
```
targetModule can be your component's name.

At last, here is my blog of how to build a logger lib with node.js for backend api, [link](https://medium.com/@lihengpro/how-to-build-a-logger-lib-with-node-js-63b163d612c7)

**Comment by xavierchow** [comment]
Thanks, let me wrap it into a Gitbook Markdown

**Comment by kenshinji** [comment]
@ChopperLee2011 one small suggestion, the demo link for creating middleware you offer above is private which I can't access. It would be better if sample code could be offered through [Gist](https://gist.github.com/).

**Comment by xavierchow** [comment]
@kenshinji Never mind, I modified it in my PR #7

**Comment by haishanh** [comment]
I agree with the logging strategy, but I don't like `bunyan` and I don't get the idea why we choose `bunyan`. Ignore me if you think it is irrelevant or off-topic.


`bunyan` is slow. According to my benchmark, it's plain string logging is 40% slower than `pino`, object logging is 20% slower than `pino`.

One of `bunyan`'s dep, `dtrace-provider` is a native module, it makes `bunyan` slow to install since it needs gyp build.

**Comment by xavierchow** [comment]
A long time ago I recall @ChopperLee2011 made a decision to use bunyan instead of other libraries (winston,morgan, log4js-node, ...) according to some investigation, but yes pino is a new lib which inspired by bunyan, we can re-evaluate.

**Comment by xavierchow** [comment]
PR is merged, and closing this one, feel free to reopen it if any questions/improvements.
